const projects = [
  {
    id: 'project3',
    title: 'Pulse Scribe',
    img: '/project3/project3.webp',
    link: '/projects/project3',
    date: '2026',
    liveLink: undefined,
    company: 'Aurelia Health',
    client: 'Aurelia Health',
    industry: 'Healthcare',
    summary: 'An ambient AI copilot that drafts clinical notes in real time, in English and Hindi.',
    metrics: [
      { value: '−62%', label: 'documentation time per patient' },
      { value: '600+', label: 'clinicians using it every day' },
      { value: '2 hrs', label: 'given back to doctors each shift' },
    ],
    tags: ['Speech AI', 'LLMs', 'Web + Mobile'],
    device: { screen: '/project3/1.webp', phone: '/project3/7.webp' },
    accent: '#0028FF',
    challenge:
      'Doctors across Aurelia Health’s 14 hospitals were spending almost a third of every shift on documentation, typing notes after each consultation instead of looking at the patient in front of them.',
    solution:
      'We built Pulse Scribe, an ambient copilot that listens to consultations with consent and drafts structured clinical notes, prescriptions and discharge summaries in real time. Speech and language models were fine-tuned on de-identified conversations in English and Hindi, inside a review-first interface where every line links back to the moment it came from.',
    impact:
      'Rolled out to more than 600 clinicians on web and mobile, Pulse Scribe cut documentation time per patient by 62% and gave doctors back almost two hours every shift, with nothing reaching the record without a doctor’s sign-off.',
    primary: '#2D2D2D',
    accentColor: '#FCFBF7',
    secondary: '#F2EEE7',
    fillColor: '#F2F3F4',
    menuColor: 'gold',
    menuFontColor: '#2D2D2D',
    fluidColor: '#0028FF',
    images: [
      {
        src: '/project3/video.mp4',
        tag: 'video',
        isRight: false,
      },
      {
        src: '/project3/7.webp',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project3/6.webp',
        tag: 'small',
        isRight: true,
      },
      {
        src: '/project3/video2.mp4',
        tag: 'video',
        isRight: false,
      },
      {
        src: '/project3/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project3/5.webp',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project3/8.webp',
        tag: 'small',
        isRight: true,
      },
      {
        src: '/project3/2.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project3/3.webp',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'Pulse Scribe is an ambient clinical documentation copilot built for Aurelia Health, a network of 14 multispecialty hospitals. With patient consent, it listens to consultations and drafts structured clinical notes, prescriptions and discharge summaries in real time.',
      'We fine-tuned speech and language models on de-identified medical conversations in English and Hindi, and wrapped them in a review-first interface. Every generated line links back to the moment in the consultation it came from, and nothing reaches the patient record without a doctor’s sign-off.',
      'Rolled out to more than 600 clinicians across web and mobile, Pulse Scribe cut documentation time per patient by 62% and gave doctors back almost two hours every shift.',
    ],
  },
  {
    id: 'project4',
    title: 'Freightmind',
    img: '/project4/project4.webp',
    link: '/projects/project4',
    date: '2025',
    company: 'Corvex Logistics',
    client: 'Corvex Logistics',
    industry: 'Logistics',
    summary: 'Forecasting and dispatch intelligence for 40,000 shipments a day across 120 cities.',
    metrics: [
      { value: '94%', label: 'forecast accuracy' },
      { value: '−18%', label: 'empty-mile runs' },
      { value: '120', label: 'cities in one live view' },
    ],
    tags: ['Forecasting', 'AI Agents', 'Optimisation'],
    device: { screen: '/project4/1.webp', panel: '/project4/2.webp' },
    accent: '#5C58EB',
    challenge:
      'Corvex planned 40,000 daily shipments from a dozen spreadsheets and phone calls. Demand spikes and hub congestion were spotted too late, so trucks ran empty while others missed their windows.',
    solution:
      'Freightmind pairs demand-forecasting models trained on five years of shipment history with planning agents that propose routes, balance loads and flag delays hours ahead. Every recommendation arrives with a plain-language reason that planners can accept, edit or reject.',
    impact: 'One live command centre replaced the spreadsheets. Forecast accuracy rose to 94%, empty-mile runs fell by 18%, and planners now spend their mornings on exceptions instead of data entry.',
    liveLink: undefined,
    primary: '#263745',
    accentColor: '#f0f4f1',
    secondary: '#F3F5F7',
    fillColor: '#E0DFFC',
    menuColor: '#5C58EB',
    menuFontColor: '#f0f4f1',
    fluidColor: '#A3A714',
    images: [
      {
        src: '/project4/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project4/2.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/3.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/4.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project4/5.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/6.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/7.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project4/8.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project4/9.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/10.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project4/11.webp',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'Freightmind is the forecasting and dispatch intelligence platform we built for Corvex Logistics, a freight and last-mile operator moving 40,000 shipments a day across 120 cities.',
      'It pairs demand-forecasting models trained on five years of shipment history with planning agents that propose routes, balance loads and flag delays hours before they happen. Each recommendation comes with a plain-language reason that planners can accept, edit or reject.',
      'One live command center replaced a dozen spreadsheets. Forecast accuracy rose to 94%, empty-mile runs dropped by 18%, and planners now spend their mornings on exceptions instead of data entry.',
    ],
  },
  {
    id: 'project5',
    title: 'Vault Search',
    img: '/project5/project5.webp',
    link: '/projects/project5',
    date: '2025',
    company: 'Solenne Capital',
    client: 'Solenne Capital',
    industry: 'Finance',
    summary: 'A private, permission-aware knowledge assistant over 1.2 million documents.',
    metrics: [
      { value: '1.2M', label: 'documents searchable' },
      { value: '95%+', label: 'answer accuracy' },
      { value: 'Minutes', label: 'not days, for research' },
    ],
    tags: ['RAG', 'Enterprise Search', 'Private Cloud'],
    device: { screen: '/project5/1.webp', panel: '/project5/6.webp' },
    accent: '#002AB0',
    challenge: 'Two decades of deal memos, contracts and board decks lived across drives and data rooms. Analysts spent days hunting for clauses, and any AI tool had to respect strict access rules.',
    solution:
      'We built Vault Search, a retrieval-augmented assistant that indexes 1.2 million documents and honours every existing permission. Answers cite the exact page and clause, and a 2,000-question evaluation suite runs on every release.',
    impact: 'Deployed entirely inside Solenne’s own cloud, Vault Search answers thousands of questions a week with accuracy above 95%, turning research that took days into minutes.',
    liveLink: undefined,
    primary: '#000000',
    accentColor: '#f0f4f1',
    secondary: '#FAFAFA',
    fillColor: '#f2f2f2',
    menuColor: '#FFD54F',
    menuFontColor: '#000000',
    fluidColor: '#002AB0',
    images: [
      {
        src: '/project5/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/2.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/3.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project5/4.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project5/5.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/6.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/7.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/8.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project5/9.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/project5/10.webp',
        tag: 'medium',
        isRight: false,
      },
    ],
    desc: [
      'Vault Search is a private knowledge assistant for Solenne Capital, an investment firm with two decades of deal memos, contracts, board decks and research notes.',
      'Our retrieval-augmented generation (RAG) system indexes 1.2 million documents and respects every existing access permission, so analysts only see answers drawn from files they are allowed to open.',
      'Every answer cites the exact page and clause. A suite of 2,000 expert-written questions runs on every release to keep accuracy above 95%.',
      'Deployed inside Solenne’s own cloud, Vault Search answers thousands of questions a week and turns days of research into minutes.',
    ],
  },
  {
    id: 'project1',
    title: 'Muse',
    img: '/project1/project1.webp',
    link: '/projects/project1',
    date: '2026',
    company: 'Brightlane Retail',
    client: 'Brightlane Retail',
    industry: 'Retail',
    summary: 'A conversational shopping assistant that curates looks from 80,000 products.',
    metrics: [
      { value: '3.4×', label: 'conversion for shoppers who chat' },
      { value: '−27%', label: 'fewer returns' },
      { value: '80K', label: 'products, always in stock' },
    ],
    tags: ['Conversational AI', 'Recommendations', 'Web + App'],
    device: { screen: '/project1/1.webp', phone: '/project1/2.webp' },
    accent: '#FF573E',
    challenge: 'Brightlane’s shoppers knew the occasion, not the product. Search and filters across 80,000 items left them scrolling, and too many orders came back because of the wrong fit or style.',
    solution:
      'Muse lets shoppers describe what they need in their own words. It understands style, budget and occasion, while a recommendation engine and a real-time inventory agent keep every suggestion in stock and in size, on the web and in the Brightlane app.',
    impact: 'Within three months of launch, shoppers who chat with Muse convert 3.4× more often and return 27% fewer items, and average order value is up 22%.',
    livelink: undefined,
    primary: '#000000',
    accentColor: '#f0f4f1',
    secondary: '#F9F9F9',
    fillColor: '#ebfaf8',
    menuColor: '#00a8c1',
    menuFontColor: '#f0f4f1',
    fluidColor: '#FF573E',
    images: [
      {
        src: '/project1/video.mp4',
        tag: 'video',
        isRight: false,
      },
      {
        src: '/project1/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/2.webp',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project1/7.webp',
        tag: 'small',
        isRight: true,
      },
      {
        src: '/project1/5.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/6.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/8.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project1/3.webp',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/project1/4.webp',
        tag: 'small',
        isRight: true,
      },
    ],
    desc: [
      'Muse is a conversational shopping assistant for Brightlane Retail, on the web and inside the Brightlane app. Shoppers describe what they need in their own words, and Muse understands style, budget and occasion to curate picks from a catalog of 80,000 products.',
      'Behind the conversation, a recommendation engine and a real-time inventory agent keep every suggestion in stock and in size. Within three months of launch, shoppers who chat with Muse convert 3.4× more often and return 27% fewer items.',
    ],
  },
  {
    id: 'project2',
    title: 'Lumora Credit',
    img: '/project2/project2.webp',
    link: '/projects/project2',
    date: '2024',
    company: 'Lumora',
    client: 'Lumora',
    industry: 'Fintech',
    summary: 'An AI underwriting copilot that explains every credit decision.',
    metrics: [
      { value: '<10 min', label: 'from application to decision' },
      { value: '10 weeks', label: 'from idea to launch' },
      { value: 'Seed', label: 'round closed on the product' },
    ],
    tags: ['Underwriting', 'Explainable AI', 'Founder MVP'],
    device: { screen: '/project2/1.webp', panel: '/project2/3.webp' },
    accent: '#0E0063',
    challenge: 'Lumora’s two founders had a bold idea for small-business lending and ten weeks to prove it to investors and partner banks, without a data or engineering team of their own.',
    solution:
      'We designed and shipped Lumora Credit end to end: data pipelines that read bank statements, GST filings and payslips, risk models that explain each decision in plain language, an underwriting dashboard and a borrower application flow, with compliance built in from day one.',
    impact: 'Application review dropped from three days to under ten minutes. The product helped the founders close their seed round and now powers lending decisions for their first partner banks.',
    liveLink: undefined,
    primary: '#0e0063',
    accentColor: '#f0f4f1',
    secondary: '#fbfbfc',
    fillColor: '#e1e1f9',
    menuColor: '#170053',
    menuFontColor: '#f0f4f1',
    fluidColor: '#E8FFC8',
    images: [
      {
        src: '/project2/video.mp4',
        tag: 'video',
        isRight: true,
      },
      {
        src: '/project2/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project2/2.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/project2/3.webp',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'Lumora Credit is an AI underwriting copilot for Lumora, a two-founder fintech that came to us with a bold idea and ten weeks to prove it.',
      'The copilot reads bank statements, GST filings and payslips, extracts every transaction, and scores credit risk with models that explain each decision in language a loan officer, and a regulator, can follow.',
      'We designed, built and launched the product end to end: data pipelines, risk models, an underwriting dashboard and a borrower application flow, with security and compliance built in from day one.',
      'Lumora Credit cut application review time from three days to under ten minutes, helped the founders close their seed round, and now powers lending decisions for their first partner banks.',
    ],
  },
];
export default projects;
